### ISSUE TITLE
论文复现验收：TIPC

### ISSUE THREAD

**Issue by shiyutang** [kongdebug/BIT-CD-Paddle#2]
TIPC需要补充整体时间截图吧

**Comment by kongdebug** [comment]
![图片](https://user-images.githubusercontent.com/52785738/164203882-920056dd-7d29-4e8c-b276-675d1f1a0432.png)
![图片](https://user-images.githubusercontent.com/52785738/164203929-cbc789e0-8e29-4371-9ad4-da3ae21e1e6e.png)
![图片](https://user-images.githubusercontent.com/52785738/164203965-4b16e274-f5a2-4a7c-bb54-d3d2fc8b1ee4.png)
![图片](https://user-images.githubusercontent.com/52785738/164203998-485dfd46-6c79-4d6c-aca3-c0523e0ed219.png)
![图片](https://user-images.githubusercontent.com/52785738/164204091-3daf0405-371a-4978-a1c5-4e7154ac2c3c.png)

**Comment by shiyutang** [comment]
好的～可以补充在readme
