### ISSUE TITLE
论文复现验收

### ISSUE THREAD

**Issue by shiyutang** [kongdebug/BIT-CD-Paddle#3]
评估结果：
<img width="782" alt="image" src="https://user-images.githubusercontent.com/34859558/164955991-d7a66182-ffad-4420-a174-b959565c7c04.png">

**Comment by shiyutang** [comment]
训练指令应该修改为：python tutorials/train/change_detection/bit_train.py
 --data_dir=../../data/LEVIR-CD --out_dir=output/BIT/

**Comment by kongdebug** [comment]
诗雨姐，按照您切割的结果评估，是89.51%大于89.31的，这算通过了吗

**Comment by shiyutang** [comment]
训练结果
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/34859558/164956125-6de8a27e-263f-4e83-acb1-fe7c6854852c.png">

**Comment by shiyutang** [comment]
嗯嗯，但是这个sample数量为什么不一样需要看下。

**Comment by kongdebug** [comment]
> 嗯嗯，但是这个sample数量为什么不一样需要看下。

我这边再试了一下，test的数量是2048的
![DO_{CXASD37)UXB_1$J_I`8](https://user-images.githubusercontent.com/52785738/164956732-051a63e6-bcee-4172-a115-a226956bee8a.png)

**Comment by kongdebug** [comment]
> 嗯嗯，但是这个sample数量为什么不一样需要看下。

诗雨姐，这是我测试文件数量的ai studio项目链接，麻烦您看一下：https://aistudio.baidu.com/studio/project/partial/verify/3875161/0e84679d86ce4e6082d2707abdbd6114

**Comment by kongdebug** [comment]
这是数据集的链接：https://aistudio.baidu.com/aistudio/datasetdetail/136610

**Comment by kongdebug** [comment]
我这边将LEVIR数据集切割好后，生成的.txt均以上传ai studio，链接：https://aistudio.baidu.com/aistudio/datasetdetail/141604

**Comment by shiyutang** [comment]
我重新做一次数据切分看看

**Comment by kongdebug** [comment]
好的，麻烦您了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月24日(周日) 下午2:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kongdebug/BIT-CD-Paddle] 论文复现验收 (Issue #3)




 
我重新做一次数据切分看看

**Comment by shiyutang** [comment]
TIPC结果正常:
<img width="804" alt="image" src="https://user-images.githubusercontent.com/34859558/164959629-82b4f087-1be7-4ccc-9c74-c5985ddcb776.png">
![image](https://user-images.githubusercontent.com/34859558/164959769-6d751f4c-5ef7-4cc3-aad8-5aff63bd28eb.png)

**Comment by shiyutang** [comment]
```python data/spliter-cd.py --image_folder ../data/LEVIR-CD --block_size 256 --save_folder ../LEVIR-CD```
数据问题已经解决，image_folder和save_folder不能为同一个目录，最好在相同时在代码中增加报错提示。

**Comment by kongdebug** [comment]
原来是这样子，好的明白了～辛苦诗雨姐



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月24日(周日) 下午2:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kongdebug/BIT-CD-Paddle] 论文复现验收 (Issue #3)




 
python data/spliter-cd.py --image_folder ../data/LEVIR-CD --block_size 256 --save_folder ../LEVIR-CD
 数据问题已经解决，image_folder和save_folder不能为同一个目录，最好在相同时在代码中增加报错提示。

**Comment by kongdebug** [comment]
![image](https://user-images.githubusercontent.com/52785738/164966814-5a11ee7a-87f6-43db-97d6-0136f850c18d.png)
已经更改，谢谢您
